# Generated by Django 3.2.16 on 2023-01-18 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=256)),
                ('next', models.CharField(max_length=256)),
                ('previous', models.CharField(max_length=256)),
                ('filename', models.CharField(max_length=64)),
            ],
        ),
    ]
