# Generated by Django 3.2.16 on 2023-01-19 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.IntegerField(choices=[(1, 'people'), (2, 'planets'), (3, 'films'), (4, 'species'), (5, 'vehicles'), (6, 'starships')])),
                ('filename', models.CharField(max_length=64)),
                ('created', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
